// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerdeCim.Models;

#nullable disable

namespace PerdeCim.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260520071507_Kullanici")]
    partial class Kullanici
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PerdeCim.Models.Perde", b =>
                {
                    b.Property<int>("PerdeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndirimOrani")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KumasTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerdeAciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerdeAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerdeFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerdeGorsel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerdeModeli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerdeId");

                    b.ToTable("Perdeler");
                });

            modelBuilder.Entity("PerdeCim.Models.Satici", b =>
                {
                    b.Property<int>("SaticiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaticiAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaticiCv")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaticiFoto")
                        .HasColumnType("TEXT");

                    b.HasKey("SaticiId");

                    b.ToTable("Saticilar");
                });

            modelBuilder.Entity("PerdeCim.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("userName")
                        .HasColumnType("TEXT");

                    b.Property<string>("userPass")
                        .HasColumnType("TEXT");

                    b.Property<string>("userRole")
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
